# SELECT RANKED.ID,
#     CASE
#         WHEN SIZE_RANK / CNT <= 0.25 THEN "CRITICAL"
#         WHEN SIZE_RANK / CNT <= 0.50 THEN "HIGH"
#         WHEN SIZE_RANK / CNT <= 0.75 THEN "MEDIUM"
#         ELSE "LOW"
#     END AS COLONY_NAME    
# FROM (
#     SELECT *, 
#     COUNT(ID) OVER () AS CNT, 
#     RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK
#     FROM ECOLI_DATA
# ) AS RANKED
# ORDER BY ID


SELECT ID,
    CASE 
        WHEN NTILE_GROUP = 1 THEN "CRITICAL"
        WHEN NTILE_GROUP = 2 THEN "HIGH"
        WHEN NTILE_GROUP = 3 THEN "MEDIUM"
        ELSE "LOW"
    END AS COLONY_NAME
FROM (
    SELECT ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS NTILE_GROUP
    FROM ECOLI_DATA
) AS NTILED
ORDER BY ID