-- 코드를 입력하세요

SELECT U.USER_ID, U.NICKNAME, G.PRICE_SUM AS TOTAL_SALES
FROM USED_GOODS_USER AS U
INNER JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS PRICE_SUM
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
    HAVING PRICE_SUM >= 700000
) AS G
    ON G.WRITER_ID = U.USER_ID
ORDER BY TOTAL_SALES


# SELECT *
# FROM USED_GOODS_BOARD
# WHERE STATUS = "DONE"
# GROUP BY WRITER_ID
# HAVING SUM(PRICE) >= 700000

























# SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD AS B
# LEFT JOIN USED_GOODS_USER AS U
#     ON B.WRITER_ID = U.USER_ID
# -- 완료된 중고거래 STATUS="DONE"
# WHERE B.STATUS = "DONE"
# -- 겹치지 않는 USER_ID를 기준으로 GROUP BY
# GROUP BY U.USER_ID
# HAVING TOTAL_SALES >= 700000
# ORDER BY TOTAL_SALES