-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS AS I
WHERE EXISTS (
    SELECT 1
    FROM ANIMAL_OUTS AS O
    WHERE I.ANIMAL_ID = O.ANIMAL_ID
        AND I.DATETIME > O.DATETIME
)
ORDER BY I.DATETIME




# SELECT I.ANIMAL_ID, O.NAME
# FROM ANIMAL_INS AS I
# INNER JOIN ANIMAL_OUTS AS O
#     ON I.ANIMAL_ID = O.ANIMAL_ID
# -- 보호시작일 (I.DATETIME) 보다 입양일 (O.DATETIME)이 더 빠른 동물 조회 조건
# WHERE I.DATETIME > O.DATETIME 
# ORDER BY I.DATETIME