
SELECT MONTH(START_DATE) AS MONTH, 
    CAR_ID,
    COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
    AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC







# SELECT 
#     MONTH(START_DATE) AS MONTH,
#     CAR_ID, 
#     COUNT(CAR_ID) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# GROUP BY CAR_ID, MONTH(START_DATE)
# # HAVING RECORDS >= 5
# ORDER BY MONTH, CAR_ID DESC


# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY











# WITH GROUPED AS
# (
#     SELECT *
#     FROM (
#         SELECT *, 
#             COUNT(CAR_ID) OVER(PARTITION BY CAR_ID) AS TOTAL_CNT
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         ) AS C
#     WHERE C.TOTAL_CNT >= 5
#         AND C.START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
#     GROUP BY MONTH(C.START_DATE), C.CAR_ID
#     # HAVING C.START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
# )

# SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(H.CAR_ID) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
# WHERE H.CAR_ID IN (
#     SELECT G.CAR_ID
#     FROM GROUPED AS G)
#     AND H.START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
# GROUP BY H.CAR_ID, MONTH(H.START_DATE)
# ORDER BY MONTH, H.CAR_ID DESC


# SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(*) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
# WHERE H.CAR_ID IN (
#         SELECT CAR_ID
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE MONTH(START_DATE) BETWEEN 8 AND 10
#         GROUP BY CAR_ID
#         HAVING COUNT(*) >= 5)
#     AND MONTH(H.START_DATE) BETWEEN 8 AND 10
# GROUP BY MONTH(H.START_DATE), H.CAR_ID
# ORDER BY MONTH, H.CAR_ID DESC

# # SELECT CAST(DATE_FORMAT(f.START_DATE, '%c') AS UNSIGNED) MONTH, f.CAR_ID, COUNT(*) RECORDS
# SELECT MONTH(START_DATE) MONTH, f.CAR_ID, COUNT(*) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY f,
#      (SELECT CAR_ID, COUNT(*) TOTAL
#       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#       WHERE START_DATE >= '2022-08-01' AND
#             START_DATE <= '2022-10-31'
#       GROUP BY CAR_ID
#       HAVING COUNT(*) >= 5) s
# WHERE f.CAR_ID = s.CAR_ID AND MONTH(f.START_DATE) BETWEEN 8 AND 10
# GROUP BY DATE_FORMAT(f.START_DATE, '%c'), f.CAR_ID
# HAVING COUNT(*) > 0
# ORDER BY MONTH, CAR_ID DESC;