SELECT F.ID, G.FISH_NAME, G.MAX_LEN AS LENGTH
FROM FISH_INFO AS F
INNER JOIN (
    SELECT I.FISH_TYPE, N.FISH_NAME, MAX(I.LENGTH) AS MAX_LEN
    FROM FISH_INFO AS I
    INNER JOIN FISH_NAME_INFO AS N
        ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY I.FISH_TYPE, N.FISH_NAME
) AS G
    ON F.LENGTH = G.MAX_LEN AND F.FISH_TYPE = G.FISH_TYPE
ORDER BY F.ID


# SELECT I.FISH_TYPE, N.FISH_NAME, MAX(I.LENGTH) AS MAX_LEN
# FROM FISH_INFO AS I
# INNER JOIN FISH_NAME_INFO AS N
#     ON I.FISH_TYPE = N.FISH_TYPE
# GROUP BY I.FISH_TYPE, N.FISH_NAME























# -- 코드를 작성해주세요
# # SELECT I.FISH_TYPE, N.FISH_NAME, MAX(I.LENGTH) AS MAX_LENGTH
# # FROM FISH_INFO AS I
# # JOIN FISH_NAME_INFO AS N
# #     ON I.FISH_TYPE = N.FISH_TYPE
# # GROUP BY I.FISH_TYPE, N.FISH_NAME


# SELECT DISTINCT I.ID, G.FISH_NAME, I.LENGTH
# FROM (
#     -- GROUP BY 통해 타입, 이름별 최대 길이 구한 Inline View 활용
#     SELECT I.FISH_TYPE, N.FISH_NAME, MAX(I.LENGTH) AS MAX_LENGTH
#     FROM FISH_INFO AS I
#     JOIN FISH_NAME_INFO AS N
#         ON I.FISH_TYPE = N.FISH_TYPE
#     GROUP BY I.FISH_TYPE, N.FISH_NAME
#     ) AS G, 
#     FISH_INFO AS I
# -- 최대 길이 및 FISH_TYPE 같은 것으로 조건 걸어준다
# WHERE G.MAX_LENGTH = I.LENGTH
#     AND G.FISH_TYPE = I.FISH_TYPE
# ORDER BY I.ID