-- 코드를 입력하세요

SELECT CONCAT("/home/grep/src/", F.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS F
WHERE F.BOARD_ID = (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
ORDER BY F.FILE_ID DESC

# SELECT CONCAT("/home/grep/src/B0001/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
# FROM USED_GOODS_FILE AS F
# JOIN (
#     SELECT BOARD_ID, MAX(VIEWS) AS MAX_VIEWS
#     FROM USED_GOODS_BOARD
#     GROUP BY BOARD_ID
#     ORDER BY MAX_VIEWS DESC
#     LIMIT 1
# ) AS M
#     ON F.BOARD_ID = M.BOARD_ID
# ORDER BY F.FILE_ID DESC




# SELECT B.BOARD_ID, MAX(B.VIEWS) AS MAX_VIEWS
# FROM USED_GOODS_BOARD AS B
# JOIN USED_GOODS_FILE AS F
#     ON B.BOARD_ID = F.BOARD_ID
# GROUP BY B.BOARD_ID
# ORDER BY MAX_VIEWS DESC