-- 코드를 입력하세요


SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES AS S
LEFT JOIN BOOK AS B
    ON B.BOOK_ID = S.BOOK_ID
WHERE MONTH(S.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY







# SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
# FROM BOOK AS B
# LEFT JOIN BOOK_SALES AS S
#     ON B.BOOK_ID = S.BOOK_ID
# WHERE MONTH(S.SALES_DATE) = 1
# GROUP BY B.CATEGORY
# ORDER BY CATEGORY