-- 코드를 작성해주세요

# SELECT L.FISH_TYPE, AVG(L.LEN_NO_NULL)
SELECT COUNT(L.FISH_TYPE) AS FISH_COUNT,
    MAX(L.LEN_NO_NULL) AS MAX_LENGTH,
    L.FISH_TYPE
FROM (
    SELECT *, IFNULL(LENGTH, 10) AS LEN_NO_NULL
    FROM FISH_INFO
) AS L
GROUP BY L.FISH_TYPE
HAVING AVG(LEN_NO_NULL) >= 33
ORDER BY L.FISH_TYPE